import type { CatalogProduct } from "./types";

export const FLAGSHIP_SHOP_ID = "seed_shop_footprintshub";

export const seedProducts: CatalogProduct[] = [
  {
    id: "prod_footprints_supporter_bundle",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Footprints Supporter Bundle",
    slug: "footprints-supporter-bundle",
    subtitle: "Merch and keepsakes for early supporters",
    description:
      "A premium starter bundle for Footprints supporters with apparel, collectible print material, and future digital unlock eligibility.",
    shortDescription: "Premium supporter merch bundle.",
    productType: "bundle",
    franchise: "footprints",
    status: "active",
    priceCents: 4900,
    currency: "USD",
    sku: "FP-SUPPORTER-BUNDLE",
    inventoryQuantity: 100,
    trackInventory: true,
    imageUrl: "/product-placeholders/footprints-supporter.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: false,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { collection: "Footprints" },
  },
  {
    id: "prod_footprints_choir_supporter_pack",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Footprints Choir Supporter Pack",
    slug: "footprints-choir-supporter-pack",
    subtitle: "A deeper supporter pack for the Footprints choir movement",
    description:
      "A higher-touch bundle for choir supporters with premium merch, recognition-ready metadata, and future fan club unlock planning.",
    shortDescription: "Premium choir supporter bundle.",
    productType: "bundle",
    franchise: "footprints",
    status: "active",
    priceCents: 9900,
    currency: "USD",
    sku: "FP-CHOIR-PACK",
    inventoryQuantity: 75,
    trackInventory: true,
    imageUrl: "/product-placeholders/choir-pack.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: true,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { collectorTier: "Supporter" },
  },
  {
    id: "prod_matrix_alpha_deck",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Matrix Decoded Alpha Deck",
    slug: "matrix-decoded-alpha-deck",
    subtitle: "First-edition collector deck concept",
    description:
      "A Matrix Decoded alpha trading card deck for early collectors, designed around story, characters, game utility, and future digital twin registration.",
    shortDescription: "Alpha collector deck.",
    productType: "physical",
    franchise: "matrix_decoded",
    status: "active",
    priceCents: 3900,
    currency: "USD",
    sku: "MD-ALPHA-DECK",
    inventoryQuantity: 250,
    trackInventory: true,
    imageUrl: "/product-placeholders/alpha-deck.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: true,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { rarity: "Founder Edition" },
  },
  {
    id: "prod_matrix_booster_series_1",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Matrix Decoded Booster Pack Series 1",
    slug: "matrix-decoded-booster-pack-series-1",
    subtitle: "Series 1 randomized collector booster concept",
    description:
      "A booster pack concept for Matrix Decoded collectors. Published odds are required before selling randomized products.",
    shortDescription: "Series 1 booster pack.",
    productType: "booster_pack",
    franchise: "matrix_decoded",
    status: "active",
    priceCents: 1200,
    currency: "USD",
    sku: "MD-BOOSTER-S1",
    inventoryQuantity: 1000,
    trackInventory: true,
    imageUrl: "/product-placeholders/booster-pack.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: false,
    digitalUnlockIncluded: false,
    tokenGated: false,
    metadata: { oddsRequiredBeforeSale: true },
  },
  {
    id: "prod_team_tardee_plush_blind_box",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Team Tardee Plush Blind Box",
    slug: "team-tardee-plush-blind-box",
    subtitle: "Mystery plush collectible concept",
    description:
      "A mystery plush collectible concept for Team Tardee fans. Odds and assortment details must be published before randomized sales.",
    shortDescription: "Mystery plush collectible.",
    productType: "blind_box",
    franchise: "matrix_decoded",
    status: "active",
    priceCents: 2900,
    currency: "USD",
    sku: "TT-PLUSH-BLIND",
    inventoryQuantity: 500,
    trackInventory: true,
    imageUrl: "/product-placeholders/plush-blind-box.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: false,
    digitalUnlockIncluded: false,
    tokenGated: false,
    metadata: { oddsRequiredBeforeSale: true },
  },
  {
    id: "prod_satoshi_founder_pack",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Satoshi Founder Pack",
    slug: "satoshi-founder-pack",
    subtitle: "Founder-level Matrix Decoded collectible bundle",
    description:
      "A founder-tier collectible bundle for Matrix Decoded story supporters. This is collectible and access-oriented, not an investment product.",
    shortDescription: "Founder-tier collectible bundle.",
    productType: "bundle",
    franchise: "matrix_decoded",
    status: "active",
    priceCents: 14900,
    currency: "USD",
    sku: "MD-SATOSHI-FOUNDER",
    inventoryQuantity: 50,
    trackInventory: true,
    imageUrl: "/product-placeholders/satoshi-founder.svg",
    galleryUrls: [],
    isFeatured: false,
    isLimitedEdition: true,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { collectorTier: "Founder" },
  },
  {
    id: "prod_founder_decoder_bundle",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Founder Decoder Bundle",
    slug: "founder-decoder-bundle",
    subtitle: "Limited founder bundle with digital unlock planning",
    description:
      "A premium collector bundle concept for early Matrix Decoded supporters with future digital unlock eligibility.",
    shortDescription: "Premium founder collector bundle.",
    productType: "bundle",
    franchise: "matrix_decoded",
    status: "active",
    priceCents: 29900,
    currency: "USD",
    sku: "MD-FOUNDER-DECODER",
    inventoryQuantity: 25,
    trackInventory: true,
    imageUrl: "/product-placeholders/founder-decoder.svg",
    galleryUrls: [],
    isFeatured: true,
    isLimitedEdition: true,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { collectorTier: "Founder Edition" },
  },
  {
    id: "prod_hero_studio_fan_club_starter",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Hero Studio Fan Club Starter Pack",
    slug: "hero-studio-fan-club-starter-pack",
    subtitle: "Membership-access starter concept",
    description:
      "A starter membership bundle concept for Hero Studio fan clubs. Final fan club terms must identify official and unofficial affiliations clearly.",
    shortDescription: "Fan club membership starter concept.",
    productType: "membership",
    franchise: "hero_studio",
    status: "active",
    priceCents: 1900,
    currency: "USD",
    sku: "HS-FANCLUB-STARTER",
    inventoryQuantity: 9999,
    trackInventory: false,
    imageUrl: "/product-placeholders/fan-club.svg",
    galleryUrls: [],
    isFeatured: false,
    isLimitedEdition: false,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { membershipAccess: true },
  },
  {
    id: "prod_digital_twin_registration",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Digital Twin Registration Placeholder",
    slug: "digital-twin-registration-placeholder",
    subtitle: "Future digital ownership registration",
    description:
      "A no-cost placeholder for future digital twin registration workflows. Not available for paid checkout until policy and product rules are final.",
    shortDescription: "Future registration placeholder.",
    productType: "digital",
    franchise: "matrix_decoded",
    status: "draft",
    priceCents: 0,
    currency: "USD",
    sku: "MD-DIGITAL-TWIN-PLACEHOLDER",
    inventoryQuantity: 0,
    trackInventory: false,
    imageUrl: "/product-placeholders/digital-twin.svg",
    galleryUrls: [],
    isFeatured: false,
    isLimitedEdition: false,
    digitalUnlockIncluded: true,
    tokenGated: false,
    metadata: { hiddenUntilReady: true },
  },
  {
    id: "prod_limited_edition_footprints_poster",
    shopId: FLAGSHIP_SHOP_ID,
    title: "Limited Edition Footprints Poster",
    slug: "limited-edition-footprints-poster",
    subtitle: "Minimal collector poster for the Footprints movement",
    description:
      "A limited poster concept for Footprints supporters with premium monochrome art direction and collectible positioning.",
    shortDescription: "Limited Footprints poster.",
    productType: "physical",
    franchise: "footprints",
    status: "active",
    priceCents: 2500,
    currency: "USD",
    sku: "FP-POSTER-LE",
    inventoryQuantity: 200,
    trackInventory: true,
    imageUrl: "/product-placeholders/footprints-poster.svg",
    galleryUrls: [],
    isFeatured: false,
    isLimitedEdition: true,
    digitalUnlockIncluded: false,
    tokenGated: false,
    metadata: { edition: "Limited" },
  },
];
